import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarAndSideMenu from "./components/Navigation/NavBarAndSideMenu";
import { SideMenuProvider } from "./context/SideMenuContext";
import MainContent from "./components/MainContent/MainContent";
import NavBarHome from "./components/Navigation/NavBarHome/NavBarHome";
import { Providers } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SideMenuProvider>
            <NavBarAndSideMenu /> {/* PONER EN CONDICIONAL DE NAVBAR */}
            <MainContent>{children}</MainContent>
          </SideMenuProvider>
        </Providers>
      </body>
    </html>
  );
}
