import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarAndSideMenu from "./components/NavBarAndSideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarAndSideMenu />
        {children}
        </body>
    </html>
  );
}
